# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name: default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pytest test.py
  displayName: 'Run unit tests'